Scripts improvements & bugfixes

diff --git a/makebr b/makebr
--- a/makebr
+++ b/makebr
@@ -15,18 +15,26 @@ BASE_DIR="${PWD}"
 CONFIG_DIR="${BASE_DIR}/configs"
 BUILD=${PROJECT}_${BOARD}
 DEFCONFIG="${PROJECT}_${BOARD}_defconfig"
+EXTERNAL="../projects/${PROJECT}"
 OUTPUT="${BASE_DIR}/o-${BUILD}"
+
+# Space separated list of tools required for the build
+# (Basically the non common tools used in all *-hook scripts)
+HOSTDEPTOOLS=()
+
+. scripts/include/log || exit 1
 
 if [ ! -f "${CONFIG_DIR}/$DEFCONFIG" ]; then
 	echo "defconfig '$DEFCONFIG' not found !"
 	exit 2
 fi
 
-extra="BR2_EXTERNAL=../projects/${PROJECT}"
+extra=
+overrides=
 debug=0
 rebuild=0
 reinstall=0
-quiet=0
+make=normal
 
 while [ "${1:0:2}" == '--' ]; do
 	case $1 in
@@ -34,16 +42,21 @@ while [ "${1:0:2}" == '--' ]; do
 	 --rebuild)	rebuild=1;;
 	 --reinstall)   reinstall=1;;
 	 --debug)	debug=1;;
-	 --quiet)	quiet=1;;
+	 --brief)	make=brief;;
 	 *)
 	 	echo "--rebuild   Restart the build from scratch"
 		echo "--reinstall Force the reinstall of target without a full rebuild"
 	 	echo "--debug     Create a debug build"
-	 	echo "--quiet     Create a log file and show lesser outputs"
+	 	echo "--brief     Create a log file and show lesser outputs"
 		echo "--j <n>     Use max <n> cpus"
 	 	exit;;
 	esac
 	shift
+done
+
+for tool in ${HOSTDEPTOOLS[*]}; do
+	which $tool &> /dev/null || \
+		die "The tool '\033[1;36m$tool\033[0m' is missing and required ! Please install it before continuing ..."
 done
 
 clone_if_new() {
@@ -52,20 +65,21 @@ clone_if_new() {
 # $2 = remote repository, e.g. $BUILDROOT_REPO
 # $3 = branch name, e.g. master
 	if [ ! -d "$1" ]; then
+		log "Retreiving buildroot from upstream ..."
 
 		if ! git ls-remote --heads "$2" "$3" > /dev/null; then
-			printf "Repository %s is not accessible\n" "$2"
-			printf "Make sure that:\n"
-			printf "\t1. Your ssh key is registered at bitbucket.\n"
-			printf "\t2. You have (read) access to this repository.\n"
-			printf "\t3. The branch %s exists in the repository.\n" "$3"
+			echo
+			echo "Repository '$2' is not accessible !"
+			echo
+			echo "Make sure that:"
+			echo "  1. Your ssh key is registered at gitlab."
+			echo "  2. You have (read) access to this repository."
+			echo "  3. The branch '$3' exists in the repository."
+			echo
 			exit 1
 		fi
-		
-		printf "%s/Makefile does not exist, clone...\n" "$1"
-		printf "git clone --branch %s %s %s\n" "$3" "$2" "$1"
-
-		git clone --branch "$3" "$2" "$1" || exit $?
+		log "git clone --branch $3 $2 $1"
+		git clone --branch "$3" "$2" "$1" || die "Exit code $?"
 	fi
 }
 
@@ -80,6 +94,38 @@ elif [ $reinstall -eq 1 ]; then
 	rm -rf $OUTPUT/{final,staging} $OUTPUT/{host,images,target}/*
 fi
 
+brief() {
+	local found ret start d h m mf
+
+	start=${SECONDS}
+
+	make -C buildroot "O=$OUTPUT" $extra "${@}" 2>&1 | ( \
+		while read line; do
+			printf "%(%H:%M:%S)T %s\n" -1 "${line}"
+		done \
+		|tee -a ${BUILD}.log \
+		|grep --line-buffered --colour=never -E '>>>'
+	)
+	ret=${PIPESTATUS[0]}
+
+	d=$((SECONDS-start))
+	printf "Done in "
+	h=$((d/3600))
+	d=$((d%3600))
+	[ ${h} -eq 0 ] || { printf "%dh " ${h}; mf="02"; }
+	m=$((d/60))
+	d=$((d%60))
+	[ ${m} -eq 0 ] || { printf "%${mf}dmin " ${m}; sf="02"; }
+	printf "%${sf}ds\n" ${d}
+	
+	return ${ret}
+}
+
+normal() {
+	make -C buildroot "O=$OUTPUT" $extra "$@"
+	return $?
+}
+
 if [ ! -e "$OUTPUT" ]; then
 	mv /tmp/~debug_build.$$ "$OUTPUT/debug_build" 2>/dev/null
 	if [ $debug -eq 1 ]; then
@@ -87,52 +133,18 @@ if [ ! -e "$OUTPUT" ]; then
 		${EDITOR:-vi} "$OUTPUT/debug_build"
 		touch "$OUTPUT/debug_build"
 	fi
-	make -C buildroot "O=$OUTPUT" $extra defconfig BR2_DEFCONFIG=$CONFIG_DIR/$DEFCONFIG
-	make -C buildroot "O=$OUTPUT" $extra source
+	log "Configuring buildroot ..."
+	overrides+=" BR2_EXTERNAL=$EXTERNAL"
+	overrides+=" BR2_DEFCONFIG=$CONFIG_DIR/$DEFCONFIG"
+	overrides+=" BR2_DL_DIR=../dl"
+	$make defconfig $overrides || die "Error code $?"
+
+	log "Downloading/checking all the source packages ..."
+	$make source || die "Error code $?"
 fi
 
-quiet() {
-    local found ret start d h m mf
+log "Start building $(date)"
+$make "${@}" || die "Error code $?"
+log "Build well done $(date)"
 
-    if ! which unbuffer >/dev/null 2>&1; then
-        printf "you need to install 'unbuffer' (from package expect or expect-dev)\n" >&2
-        exit 1
-    fi
-
-    start=${SECONDS}
-
-    ( exec 2>&1; unbuffer make -C buildroot "O=$OUTPUT" $extra "${@}"; ) \
-    > >( while read line; do
-             printf "%(%H:%M:%S)T %s\n" -1 "${line}"
-         done \
-         |tee -a ${BUILD}.log \
-         |grep --colour=never -E '>>>'
-       )
-    ret=${?}
-
-    d=$((SECONDS-start))
-    printf "Done in "
-    h=$((d/3600))
-    d=$((d%3600))
-    [ ${h} -eq 0 ] || { printf "%dh " ${h}; mf="02"; }
-    m=$((d/60))
-    d=$((d%60))
-    [ ${m} -eq 0 ] || { printf "%${mf}dmin " ${m}; sf="02"; }
-    printf "%${sf}ds" ${d}
-
-    if [ ${ret} -ne 0 ]; then
-        printf "  (error code: %s)" ${ret}
-    fi
-    printf "\n"
-
-    return ${ret}
-}
-
-normal() {
-
-	make -C buildroot "O=$OUTPUT" $extra "$@"
-
-}
-echo -e "\e[1;33m>>> START" $(date) "\e[0m"
-[ $quiet -eq 1 ] && quiet "${@}" || normal "${@}"
-echo -e "\e[1;33m>>> END" $(date) "\e[0m"
+exit 0
